site_name: Shereen ESTHER
theme:
  name: material
  logo: 'assets/logo.png'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: teal
  language: en
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - abbreviations.md
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js 
extra_css:
  - stylesheets/custom.css
#   - stylesheets/extra.min.css
#   - stylesheets/bootstrap-grid.min.css
#   - stylesheets/skills.css

nav:
  - About me: 'index.md'
  - Skills:
    - All Skills: 'pages/skills/index.md'
    - Web Technologies: 'pages/skills/Web Technologies/index.md'
    - Databases: 'pages/skills/Databases/index.md'
    - Operating Systems: 'pages/skills/Operating Systems/index.md'
    - Code Repositories: 'pages/skills/Code Repositories/index.md'
    - Frameworks: 'pages/skills/Frameworks/index.md'
    - Package Managers: 'pages/skills/Package Managers/index.md'
    - IDEs: 'pages/skills/IDEs/index.md'
    - Other Skills: 'pages/skills/Other Skills/index.md'
  - Experience:
    - Surfboard Payments: 'pages/experience/Surfboard Payments/index.md'
    - Wipro Limited: 'pages/experience/Wipro Limited/index.md'
    - HP Enterprise: 'pages/experience/HP Enterprise/index.md'
  - Projects:
    - All Projects: 'pages/projects/index.md'
    - Web Projects:
      - Angular: 'pages/projects/Web Projects/angular.md'
      - ASP.NET: 'pages/projects/Web Projects/aspnet.md'
      - Other: 'pages/projects/Web Projects/other.md'
    - Machine Learning Projects: 'Projects/ML projects/index.md'